CREATE TABLE `video_research` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`sourceUrl` text NOT NULL,
	`platform` enum('facebook','instagram','youtube','tiktok','other') NOT NULL DEFAULT 'facebook',
	`competitorName` varchar(255),
	`competitorId` int,
	`s3Key` text,
	`s3Url` text,
	`status` enum('pending','downloading','downloaded','transcribing','transcribed','analyzing','analyzed','adapting','completed','failed') NOT NULL DEFAULT 'pending',
	`errorMessage` text,
	`transcript` text,
	`transcriptHook` text,
	`transcriptBody` text,
	`transcriptCta` text,
	`analysisAngle` varchar(255),
	`analysisTargetAudience` text,
	`analysisMechanic` text,
	`analysisOfferStructure` text,
	`analysisWhyItWorks` text,
	`analysisVisualPattern` text,
	`adaptHook1` text,
	`adaptHook2` text,
	`adaptHook3` text,
	`adaptBody` text,
	`adaptCta` text,
	`adaptHeygenScript` text,
	`adaptTelegramPost` text,
	`adaptNanaBananaPrompt` text,
	`fileName` varchar(512),
	`driveFolderPath` varchar(512),
	`driveFileId` varchar(255),
	`driveUrl` text,
	`adLibraryId` varchar(128),
	`language` varchar(16) DEFAULT 'de',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `video_research_id` PRIMARY KEY(`id`)
);
