CREATE TABLE `meta_ad_insights` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`campaignId` varchar(64) NOT NULL,
	`campaignName` varchar(255) NOT NULL,
	`adsetId` varchar(64),
	`adsetName` varchar(255),
	`adId` varchar(64),
	`adName` varchar(255),
	`level` enum('account','campaign','adset','ad') NOT NULL DEFAULT 'campaign',
	`spend` float DEFAULT 0,
	`impressions` bigint DEFAULT 0,
	`clicks` bigint DEFAULT 0,
	`reach` bigint DEFAULT 0,
	`ctr` float DEFAULT 0,
	`cpc` float DEFAULT 0,
	`cpm` float DEFAULT 0,
	`roas` float DEFAULT 0,
	`purchases` float DEFAULT 0,
	`leads` float DEFAULT 0,
	`costPerPurchase` float DEFAULT 0,
	`costPerLead` float DEFAULT 0,
	`frequency` float DEFAULT 0,
	`status` varchar(32),
	`objective` varchar(64),
	`dailyBudget` float,
	`dateStart` varchar(16) NOT NULL,
	`dateStop` varchar(16) NOT NULL,
	`datePreset` varchar(32),
	`rawData` json,
	`syncedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meta_ad_insights_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meta_ai_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`analysisDate` varchar(16) NOT NULL,
	`datePreset` varchar(32) DEFAULT 'last_7d',
	`summary` text,
	`topPerformers` json,
	`underperformers` json,
	`budgetRecommendations` json,
	`actionItems` json,
	`insights` json,
	`overallScore` float,
	`totalSpend` float,
	`totalRevenue` float,
	`avgRoas` float,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meta_ai_analyses_id` PRIMARY KEY(`id`)
);
